import { Metadata } from "next"

export const metadata={
    title:{
        absolut:"",
        default:"Learning next js application developement",
        template:""
    },
    description:"Generated by Next.js"
}
export default function Layout({children}){
    return(
        <section>
            {children}
            <h2>About Layout </h2>
        </section>
    )
}